name: Reusable Docker

on:
  workflow_call: {}

env:
  GHCR_NAME: ghcr.io/kt-yeh/hoyolab-geetest-webserver

jobs:
  builder:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup multiarch
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.GHCR_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=edge,branch=master
            type=ref,event=branch

      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
